export const GET_BASIC_USER_DATA = 'GET_BASIC_USER_DATA';

export const GETTING_ALL_POST = 'GETTING_ALL_POST';

export const ALL_POST_ARRIVED = 'ALL_POST_ARRIVED';

export const INITIATING_DATA = 'INITIATING_DATA';

export const USER_DATA_ARRIVED = 'USER_DATA_ARRIVED';

export const CHAT_DATA_ARRIVED = 'CHAT_DATA_ARRIVED';

export const GETTING_CHAT_DATA = 'GETTING_CHAT_DATA';

export const CHAT_OPEN = 'CHAT_OPEN';

export const CHAT_CLOSE = 'CHAT_CLOSE';